"""
cohort_shap_analysis.py — which factors drive readmission risk across the cohort?
=================================================================================
Extends the per-patient SHAP explainability (dashboard "Why this score?" panel)
to the full 984-patient cohort: mean |SHAP| per feature = average influence of
each factor on the model's readmission risk scores.

HONESTY CAVEAT (consistent with reports/model_honesty.md):
    The ranking reflects the dataset's synthetic generation logic — readmission
    was generated as a function of the condition pathway — NOT clinical
    evidence about real readmission drivers. Condition dominating this chart
    is the same finding as the honesty audit, now shown through SHAP.

Run:  python scripts/cohort_shap_analysis.py
Writes: reports/cohort_shap.md
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

import numpy as np
import pandas as pd

from app.dashboard.utils import ai_risk
from app.dashboard.utils import hospital_data as data

REPORTS = ROOT / "reports"
REPORTS.mkdir(exist_ok=True)


def compute_cohort_importance(df: pd.DataFrame) -> tuple[pd.Series, pd.Series]:
    """Mean |SHAP| (influence) and signed mean (direction) per feature, all patients."""
    model, encoders = ai_risk.load_model()
    explainer = ai_risk.load_explainer()
    enc = ai_risk._encode(df, encoders)
    X = enc[ai_risk.FEATURES]

    shap_vals = explainer.shap_values(X)
    if isinstance(shap_vals, list):          # older shap: [class0, class1]
        vals = shap_vals[1]
    elif np.ndim(shap_vals) == 3:            # current shap: (n, features, classes)
        vals = shap_vals[:, :, 1]
    else:                                    # single-output / regression-style
        vals = shap_vals

    importance = pd.Series(np.abs(vals).mean(axis=0), index=ai_risk.FEATURES)
    direction = pd.Series(vals.mean(axis=0), index=ai_risk.FEATURES)
    return importance.sort_values(ascending=False), direction


def main() -> None:
    df = data.load_patients()
    importance, direction = compute_cohort_importance(df)

    total = importance.sum()
    rows = []
    for feat, imp in importance.items():
        label = ai_risk.FEATURE_LABELS.get(feat, feat)
        share = imp / total * 100 if total else 0
        signed = direction[feat]
        arrow = "raises risk" if signed > 0 else "lowers risk"
        bar = "\u2588" * max(1, int(share / 2.5))
        rows.append((label, imp, share, arrow, bar))

    lines = [
        "# Cohort Explainability — What Drives Readmission Risk",
        "### Mean |SHAP| per feature across all 984 patients",
        "",
        "> Generated by `scripts/cohort_shap_analysis.py`. The interactive version of this",
        "> analysis is in the dashboard's **Clinical Analytics** tab; per-patient factor",
        "> breakdowns are in **Patient Intelligence**. Method: SHAP TreeExplainer on the",
        "> deployed RandomForest, class 1 (readmitted), mean absolute SHAP value per feature.",
        "",
        "## Influence ranking",
        "",
        "| Rank | Factor | Mean \\|SHAP\\| | Share of influence | Direction (avg) |",
        "|---|---|---|---|---|",
    ]
    for i, (label, imp, share, arrow, bar) in enumerate(rows, 1):
        lines.append(f"| {i} | {label} | {imp:.4f} | {share:.1f}% | {arrow} |")
    lines += [
        "",
        "## Text-scale view (share of total influence)",
        "",
    ]
    for label, imp, share, arrow, bar in rows:
        lines.append(f"- **{label}** — {share:.1f}% {bar}")
    # computed narrative — no hardcoded ranking claims
    top_label = ai_risk.FEATURE_LABELS.get(importance.index[0], importance.index[0])
    top_share = importance.iloc[0] / total * 100 if total else 0
    pathway_share = sum(importance.get(f, 0) for f in
                        ["Procedure_enc", "Cost", "Condition_enc", "Length_of_Stay"]) / total * 100
    demo_share = sum(importance.get(f, 0) for f in ["Age", "Gender_enc"]) / total * 100

    lines += [
        "",
        "## How to read this honestly",
        "",
        f"1. **Influence is diffuse, not concentrated.** The top factor is **{top_label}**",
        f"   at {top_share:.1f}% of total influence — no single factor dominates. With",
        "   correlated features (Procedure is a 1:1 proxy for Condition; Cost and Length",
        "   of Stay follow the same condition pathway), a RandomForest spreads its splits",
        "   across the correlated group, so SHAP attribution is distributed. This is",
        "   expected model behaviour, not evidence of independent risk factors.",
        f"2. **Pathway-linked factors (Procedure + Cost + Condition + Length of Stay)",
        f"   jointly hold {pathway_share:.1f}% of influence** — consistent with the model",
        "   honesty audit (`reports/model_honesty.md`), which showed readmission is",
        "   generated as a near-deterministic function of the condition pathway in this",
        "   synthetic dataset.",
        f"3. **Age and Gender together hold {demo_share:.1f}%.** The model uses demographic",
        "   splits as proxies for the same underlying signal — a pattern worth flagging",
        "   for the fairness review (`reports/fairness_check.md`). On real clinical data,",
        "   demographic influence would warrant a bias audit before deployment.",
        "4. **This is NOT clinical evidence.** The ranking reflects the dataset's",
        "   generation logic and demonstrates the explainability method. On real hospital",
        "   data, the same script would rank genuinely informative factors — and its",
        "   findings would need clinical review.",
        "",
        "## Reproduce",
        "",
        "```bash",
        "python scripts/cohort_shap_analysis.py   # regenerates this report",
        "pytest tests/test_cohort_shap.py -v      # pins the pathway share invariant",
        "```",
    ]

    (REPORTS / "cohort_shap.md").write_text("\n".join(lines) + "\n", encoding="utf-8")

    print("Cohort SHAP importance (mean |SHAP| per feature):")
    for i, (feat, imp) in enumerate(importance.items(), 1):
        print(f"  {i}. {ai_risk.FEATURE_LABELS.get(feat, feat):20} {imp:.4f}  ({imp/total*100:.1f}%)")
    print(f"\nReport written: {REPORTS / 'cohort_shap.md'}")


if __name__ == "__main__":
    main()
